name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      # - run: go mod tidy
      # - run: go test -v ./...
      - name: Run GoReleaser Dry-Run
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --clean --skip-validate --skip-publish --skip-sign
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --clean --skip-sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GH_PAT }}
      # - uses: goreleaser/goreleaser-action@v2
      #   if: success() && startsWith(github.ref, 'refs/tags/')
      #   with:
      #     version: latest
      #     args: release --rm-dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_PAT }}